#!/bin/bash

python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_20_eta_0_nres_0.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_20_eta_0_nres_1.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_20_eta_0_nres_5.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_20_eta_0_nres_10.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_20_eta_1_nres_0.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_20_eta_1_nres_1.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_20_eta_1_nres_5.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_20_eta_1_nres_10.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_60_eta_0_nres_0.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_60_eta_0_nres_1.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_60_eta_0_nres_5.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_60_eta_0_nres_10.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_60_eta_1_nres_0.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_60_eta_1_nres_1.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_60_eta_1_nres_5.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_60_eta_1_nres_10.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_100_eta_0_nres_0.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_100_eta_0_nres_1.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_100_eta_0_nres_5.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_100_eta_0_nres_10.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_100_eta_1_nres_0.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_100_eta_1_nres_1.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_100_eta_1_nres_5.json
python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/square_image_action_horizon_16_inp_t_ts_100_inp_t_ts_100_eta_1_nres_10.json

python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/base_config_square_ddim_eta_1.json

python /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/sim/run_trained_agent_rh_hparam_square.py --config /nethome/nkra3/flash7/phd_project/robomimic-nadun/robomimic/dev/hparam/config/square_inpaint/base_config_square_ddim_eta_0.json
